### ISSUE TITLE
Inference code

### ISSUE THREAD

**Issue by YOOHYOJEONG** [cvlab-epfl/MVFlow#2]
Hello. Thanks to your good thesis and code, I studied a lot.

I got a question while studying with the code you shared.
Do you happen to have any intention of releasing the inference code?
I tried to use the evaluation code, but it didn't work…...

When evaluating, the "video_path" argument (-vid, --video_path) is not applied properly, and the images in the wildtrack dataset appear to be applied continuously.

I'd like to make an inference with your model, but are you willing to release the inference code in the future?

Thank you.

**Comment by M-Eng** [comment]
Hi,

Thank you for your interest in our work, indeed the -vid option in evaluation is not working, it should have been removed.
As for the inference, we are not planning to release additional code, but the current repo contains everything needed to run inference. 
You just need to create a new dataset class specific to your data, following the same structure as the [wildtrack one]( https://github.com/cvlab-epfl/MVFlow/blob/main/dataset/wildtrack.py).

Note, however, that our model is trained on a single scene, for a specific number of cameras, and is unlikely perform well in a transfer to a different scene without prior fine-tuning.

Best,
Martin

**Comment by YOOHYOJEONG** [comment]
Thanks to your answer, I was able to evaluate and visualize with my dataset.

I have one more question, is it not possible to specify the view_id when evaluating? I changed the view_id argument in arguments.py, but it didn't work.

And...
I don't want to visualize the information related to gt when visualizing the prediction result.
So I annotated all the contents related to gt_point and person_id on visualization.py .
Nevertheless, the visualized video shows a gt box together.

Is there any other way than the way I tried?


Thank you!

**Comment by M-Eng** [comment]
To change the view_ids at evaluation time you can overwrite the value 
`config["data_conf"]["view_ids"] = ["your"], "view", "id"]` at the beginning of  evaluation.py. But as stated above the model is designed to be evaluated with the same number of views it was trained on.

There is two visualizations, one for the detection alone and one for the tracking, have you modified both?
`MVFlow/misc/visualization.py`
`MVFLow/tracker/visualization.py`

Best,
Martin

**Comment by YOOHYOJEONG** [comment]
Oh, Thank you very much!!!!!

I solved it thanks to you.
Thank you very much for your kind reply.

Thank you :)
